---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 84.252.140.251
    jenkins-agent-01:
      ansible_host: 130.193.42.189
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant